
name: android-maguro

on:
  push:
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/android-maguro.yml'
      - 'images/android/maguro/**'
      # - 'common/**'
      # - 'images/setup.sh'
      # - 'images/build.sh'
      # - 'images/commit.sh'
      # - 'images/publish-dockerhub.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Build image and publish
    runs-on: ubuntu-latest
    env:
      workdir: ${{ github.workspace }}/images/android/maguro/cyanogenmod-13.0
      config: android/maguro/cyanogenmod-13.0/config.sh
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install build dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -q install -y ubuntu-*keyring debian-*keyring ca-certificates
          apt-key list
          sudo apt-get -q update
          sudo apt-get -q install -y abootimg qemu-user-static

      - name: Build container
        run: |
          cd "${{ env.workdir }}"
          ./build.sh

      - name: Create image from container
        run: |
          cd "${{ env.workdir }}"
          ./commit.sh

      - name: Publish image on Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: ${{ github.workspace }}/images/publish-dockerhub.sh ${{ env.config }}
