
name: buildenv-android

on:
  push:
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/buildenv-android.yml'
      - 'images/build-environments/android/**'
      # - 'common/**'
      # - 'images/setup.sh'
      # - 'images/build.sh'
      # - 'images/commit.sh'
      # - 'images/publish-dockerhub.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-amd64:
    name: Build image and publish
    runs-on: ubuntu-latest
    env:
      config: build-environments/android/config.sh
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build container
        run: ${{ github.workspace }}/images/build.sh ${{ env.config }}

      - name: Create image from container
        run: ${{ github.workspace }}/images/commit.sh ${{ env.config }}

      - name: Publish image on Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: ${{ github.workspace }}/images/publish-dockerhub.sh ${{ env.config }}
