
name: compute-compile

on:
  push:
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/compute-compile.yml'
      - 'containers/environments/compute/compile/*'

  workflow_dispatch:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    env:
      workdir: ${{ github.workspace }}/containers/environments/compute/compile
      image_tag: compute:compile
      config: environments/compute/compile/config.sh
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build image from Dockerfile
        run: |
          cd "${{ env.workdir }}"
          podman build -t ${{ env.image_tag }} .

      - name: Publish image on Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: ${{ github.workspace }}/containers/publish-dockerhub.sh ${{ env.config }}
