# This is a basic workflow to help you get started with Actions

name: qemu-armhf-debian-base

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/qemu-armhf-debian-base.yml'
      - 'qemu-armhf-debian-base/**'
      - 'images/qemu-armhf-debian-base/**'
      
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
        DEBIAN_REPO: https://deb.debian.org/debian/
        DEBIAN_RELEASE: buster
        DEBIAN_VARIANT: minbase
        WORKDIR: image

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Info
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          cd .github/workflows/
          cat ${GITHUB_WORKFLOW}.yml

      # Runs a set of commands using the runners shell
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static debootstrap

      - name: Bootstrap Debian
        run: |
          cd $GITHUB_WORKSPACE/images/qemu-armhf-debian-base/
          ls -la
          mkdir -p "$WORKDIR"
          sudo qemu-debootstrap --arch=armhf "$DEBIAN_RELEASE" --variant="$DEBIAN_VARIANT" "$WORKDIR" "$DEBIAN_REPO"
          sudo echo "armhf" > "$WORKDIR/etc/hostname"
          sudo echo "deb https://deb.debian.org/debian buster main" > "$WORKDIR/etc/apt/sources.list"
          sudo echo "deb-src https://deb.debian.org/debian buster main" >> "$WORKDIR/etc/apt/sources.list"

      - name: Install base packages
        run: |
          cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/"
          sudo chroot "$WORKDIR" qemu-arm-static "apt-get update; apt-get install -y apt aptitude rsync wget vim nano git; apt-get clean"

