# This is a basic workflow to help you get started with Actions

name: qemu-armhf-debian-base

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/qemu-armhf-debian-base.yml'
      - 'qemu-armhf-debian-base/**'
      - 'images/qemu-armhf-debian-base/**'
      
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
        DEBIAN_REPO: http://deb.debian.org/debian/
        DEBIAN_RELEASE: buster
        DEBIAN_VARIANT: minbase
        WORKDIR: image

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print debug information
        run: |
          me=$(whoami)
          echo "I am $me."
          uname -a
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ls -la
          cd .github/workflows/
          cat ${GITHUB_WORKFLOW}.yml

      - name: Prepare for package installation
        run: |
          sudo apt-get update
          sudo apt-get install -y ubuntu-*keyring debian-*keyring ca-certificates
          apt-key list

      - name: Install build dependencies
        run: |
          sudo apt-get install -y qemu-user-static debootstrap coreutils

      - name: Bootstrap Debian
        run: |
          cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/"
          ls -la
          mkdir -p "$WORKDIR"
          sudo qemu-debootstrap --arch=armhf "$DEBIAN_RELEASE" --variant="$DEBIAN_VARIANT" "$WORKDIR" "$DEBIAN_REPO"

      - name: Configure bootstrapped system
        run: |
          cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/"
          me=$(whoami)
          sudo chown $me "$WORKDIR/"
          sudo cp -v hostname "$WORKDIR/etc/"
          sudo cp -v sources.list "$WORKDIR/etc/apt/"

      - name: Add qemu binary
        run: |
          cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/"
          cp -v "$(which qemu-arm-static)" "$WORKDIR"

      - name: Install additional packages
        run: |
          cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/"
          sudo chroot "$WORKDIR" qemu-arm-static bin/bash -c \
            "apt-get update; \
            apt-get install netselect-apt; \
            netselect-apt -s DEBIAN_RELEASE; \
            apt-get install -y ubuntu-*keyring debian-*keyring ca-certificates; \
            apt-key list; \
            apt-get install -y coreutils bash vim nano apt aptitude rsync wget git; \
            apt-get clean"

      - name: Create an archive
        run: |
            cd "$GITHUB_WORKSPACE/images/qemu-armhf-debian-base/$WORKDIR/"
            export archive="qemu-armhf-debian-base.tar.gz"
            sudo tar -czvf "../$archive" .
            me=$(whoami)
            sudo chown $me "../$archive"

      - name: Release archive on GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: qemu-armhf-debian-base.tar.gz
